# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 5) do

  create_table "bookings", :force => true do |t|
    t.column "performance_id", :integer
    t.column "name",           :string
    t.column "phone",          :string
    t.column "email",          :string
    t.column "waged",          :integer, :default => 2
    t.column "unwaged",        :integer, :default => 0
    t.column "notify_me",      :boolean
    t.column "confirmed",      :boolean, :default => false
    t.column "comments",       :text
  end

  create_table "members", :force => true do |t|
    t.column "first_name", :string
    t.column "last_name",  :string
    t.column "email",      :string
  end

  create_table "performances", :force => true do |t|
    t.column "time",    :datetime
    t.column "show_id", :integer
  end

  create_table "roles", :force => true do |t|
    t.column "member_id", :integer
    t.column "show_id",   :integer
    t.column "job",       :string
    t.column "character", :string
    t.column "position",  :integer, :default => 0
    t.column "type",      :string
  end

  create_table "shows", :force => true do |t|
    t.column "name",          :string,                                              :default => "", :null => false
    t.column "permalink",     :string,                                              :default => "", :null => false
    t.column "year",          :integer
    t.column "month",         :integer
    t.column "description",   :text
    t.column "is_current",    :boolean
    t.column "splash_page",   :text
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
    t.column "waged_price",   :integer,  :limit => 2, :precision => 2, :scale => 0
    t.column "unwaged_price", :integer,  :limit => 2, :precision => 2, :scale => 0
  end

end
